# Execute gitlab construction to sprin boot project

# Author = Cristian Freire


include:
  - remote: 'https://gitlab.seps.gob.ec/admincicd/seps-gitlab-runner-pipeline-shared-lib/-/raw/master/java/.springBootServicePipelineV2.yml'
